# ElectroVision AI - YOLO Training Configuration

# Dataset paths (relative to this config file)
train: dataset/images/train
val: dataset/images/val
test: dataset/images/test

# Number of classes
nc: 77

# Class names for electrical components (single source of truth)
names:
  # Protection & Safety Components
  0: 'main_breaker'            # Main circuit breaker - cuts entire power
  1: 'mcb'                     # Miniature circuit breaker - overload & short circuit protection
  2: 'fuse'                    # Fuse - burns out during overcurrent
  3: 'distribution_panel'      # Power distribution panel - houses all breakers
  4: 'isolator'                # Isolator - used to cut line for maintenance
  5: 'overload_relay'          # Motor overload protection device
  6: 'lightning_arrester'      # Lightning protection device
  7: 'emergency_stop'          # Emergency stop button
  
  # Control & Switching Components
  8: 'contactor'               # Contactor - switching for motors and large loads
  9: 'relay'                   # Relay - electrically controlled switch
  10: 'single_switch'          # Single switch - basic on/off control
  11: 'double_switch'          # Double switch - dual control
  12: 'two_way_switch'         # Two-way switch - control from two locations
  13: 'push_button_switch'     # Push button switch - momentary contact
  14: 'panel_indicator'        # Panel indicator light
  
  # Wiring & Connection Components
  15: 'wire'                   # Single wire - basic circuit connection
  16: 'cable'                  # Multi-core cable - power transmission
  17: 'conduit'                # Conduit - protective pipe for cables
  18: 'cable_tray'             # Cable tray - organized cable management
  19: 'lug'                    # Cable lug - terminal for cable ends
  20: 'terminal_block'         # Terminal block - wire connection point
  21: 'cable_marker'           # Cable identification marker
  22: 'expansion_joint'        # Cable tray connection joint
  
  # Lighting Components
  23: 'led_light'              # LED light - energy efficient illumination
  24: 'round_light'            # Round incandescent bulb
  25: 'tube_light'             # Tube light - fluorescent lighting
  26: 'emergency_light'        # Emergency light - backup illumination
  27: 'halogen_light'          # Halogen light - high-intensity illumination
  28: 'street_light'           # Street light - outdoor lighting
  29: 'exit_sign'              # Exit sign - emergency exit indication
  30: 'fire_button_sign'       # Fire alarm button sign
  
  # Power & Connection Points
  31: 'power_socket'           # Power socket - general power connection
  32: 'industrial_socket'      # Industrial socket - high-power equipment
  33: 'single_phase_connection_point' # Single phase connection point
  34: 'three_phase_connection_point'  # Three phase connection point
  
  # Earthing & Grounding
  35: 'earth_rod'              # Earth rod - grounding electrode
  36: 'earthing_wire'          # Earthing wire - grounding conductor
  37: 'earth_pit'              # Earth pit - grounding excavation
  38: 'earth_busbar'           # Earth busbar - grounding distribution
  39: 'earth_terminal'         # Earth terminal - grounding connection
  40: 'lightning_protection'   # Lightning protection system
  
  # Measurement & Instrumentation
  41: 'voltmeter'              # Voltmeter - voltage measurement
  42: 'ammeter'                # Ammeter - current measurement
  43: 'power_meter'            # Power meter - power measurement
  44: 'energy_meter'           # Energy meter - kWh measurement
  45: 'multifunction_meter'    # Multifunction meter - multiple parameter measurement
  46: 'frequency_meter'        # Frequency meter - Hz measurement
  47: 'power_factor_meter'     # Power factor meter - power factor measurement
  48: 'ct'                     # Current transformer - current measurement
  49: 'pt'                     # Potential transformer - voltage measurement
  
  # Power Equipment
  50: 'transformer'            # Transformer - voltage conversion
  51: 'ups'                    # UPS - uninterruptible power supply
  52: 'inverter'               # Inverter - DC to AC conversion
  53: 'battery_bank'           # Battery bank - backup power storage
  54: 'solar_panel'            # Solar panel - renewable energy generation
  55: 'generator'              # Generator - backup power generation
  56: 'motor'                  # Electric motor - mechanical drive
  
  # Sensors & Detection
  57: 'sensor'                 # Motion sensor - movement detection
  58: 'smoke_detector'         # Smoke detector - fire detection
  59: 'smoke_detector_led'     # Smoke detector with LED indicator
  60: 'motion_detector'        # Motion detector - movement sensing
  61: 'fire_button'            # Fire alarm button - manual fire alarm
  
  # Alarm & Signaling
  62: 'buzzer'                 # Buzzer - audio alarm device
  63: 'alarm_system'           # Alarm system - complete security system
  64: 'pilot_lamp'             # Pilot lamp - status indication
  65: 'signal_lamp'            # Signal lamp - control indication
  66: 'fire_alarm_panel'       # Fire alarm panel - fire system control
  
  # Access & Control
  67: 'access_control'         # Access control - entry management
  68: 'ventilation_fan'        # Ventilation fan - air circulation
  
  # Documentation & Labeling
  69: 'label_tag'              # Label tag - component identification
  70: 'circuit_diagram_legend' # Circuit diagram legend - symbol explanation
  
  # Placeholder classes for future expansion
  71: 'reserved_71'            # Reserved for future use
  72: 'reserved_72'            # Reserved for future use
  73: 'reserved_73'            # Reserved for future use
  74: 'reserved_74'            # Reserved for future use
  75: 'reserved_75'            # Reserved for future use
  76: 'reserved_76'            # Reserved for future use

# Training hyperparameters
epochs: 100
batch_size: 16
img_size: 640
workers: 8

# Optimization settings
optimizer: 'AdamW'
lr0: 0.01
weight_decay: 0.0005
momentum: 0.937

# Augmentation settings
augment: true
mixup: 0.1
copy_paste: 0.3
degrees: 10.0
translate: 0.1
scale: 0.5
shear: 2.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4

# Validation settings
val_split: 0.2
save_period: 10
patience: 50

# Model architecture
model: 'yolov8n.pt'  # Starting model (nano for faster training)
pretrained: true

# Hardware settings
device: ''  # Auto-detect (cuda if available, else cpu)
multi_scale: false
single_cls: false

# Logging and saving
project: 'runs/train'
name: 'electrical_components'
save: true
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
visualize: false
augment_val: false
cache: false
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: false
bucket: ''
cfg: ''
weights: ''
imgsz: 640

# Training Configuration
augmentation:
  horizontal_flip: true
  vertical_flip: false
  rotation: 15
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1

# Model Output Configuration
confidence_threshold: 0.5
iou_threshold: 0.45
max_detections: 100

# Export Configuration
export_formats:
  - "onnx"
  - "torchscript"
  - "tflite"
